name: Upload Go test results

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
      - name: Install dependencies
        run: go get .
      - name: Test with Go
        run: go test -json > TestResults-1.23.json
      - name: Upload Go test results
        uses: actions/upload-artifact@v4
        with:
          name: Go-results-1.23
          path: TestResults-1.23.json
