name: Upload Go test results

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  GOVERSION: '1.23'

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: $GOVERSION
      - name: Install dependencies
        run: go get .
      - name: Test with Go
        run: go test -json > TestResults-$GOVERSION.json
      - name: Upload Go test results
        uses: actions/upload-artifact@v4
        with:
          name: Go-results-$GOVERSION
          path: TestResults-$GOVERSION.json
